### PR TITLE
Rethrow exception so that job status is handled

### PR DESCRIPTION
**Pull request by georgebohnisch**
Closes laravel-notification-channels/twilio#60

### CODE REVIEW

**Review by m2jobe — APPROVED** [review]

**Comment by m2jobe** [comment]
Tested and looks good

**Comment by klimov-paul** [comment]
Such change may break existing applications.
For example: Twilio client throws an exception in case of invalid receiver phone number or in case receiver phone number belongs to unsupported region.
See:
* https://www.twilio.com/docs/api/errors/21608
* https://www.twilio.com/docs/api/errors/21211
* https://www.twilio.com/docs/api/errors/21614
* https://www.twilio.com/docs/api/errors/21408

If this PR accepted Laravel application may easily end up in 500 error in case user entered incorrect phone number by a mistake.

**Comment by klimov-paul** [comment]
Enhanced solution provided via #73

**Comment by atymic** [comment]
Thanks for the PR, introduced in #90 :)

**Pull request closed without merging**
