### PR TITLE
Add 'twilio.to' config option allowing to set universal receiver

### PR DESCRIPTION
**Pull request by klimov-paul**
Relates to #72 (fix partially).

Adds 'twilio.to' config option, allowing to set universal receiver phone number.

### CODE REVIEW

**Review by atymic — COMMENTED** [review]
Wouldn't this be better handled by the end user in the routing?

I.e. in your model:

```php
// user model 

public function routeNotificationsForTwilio() {
	if (app()->environment('local')) {
		return config('twilio.default_to', $this->phone)
	}

	return $this->phone;
}

**Comment by atymic** [comment]
I think a log file would make more sense IMO.

**Comment by klimov-paul** [comment]
> Wouldn't this be better handled by the end user in the routing?

It would require adjusting all models, which may represent receivers.

Such solition is consistent to Laravel mail one. See [Mail & Local Development](https://laravel.com/docs/6.x/mail#mail-and-local-development)

**Comment by atymic** [comment]
> It would require adjusting all models, which may represent receivers.
> 
> Such solition is consistent to Laravel mail one. See [Mail & Local Development](https://laravel.com/docs/6.x/mail#mail-and-local-development)

Fair enough, but I think in this case a log is a much better idea - sending messages costs a fair bit.

**Comment by klimov-paul** [comment]
No one says there should not be a log driver. It is a matter for the another changeset.

For the manual QA it is sometims crucial to test actual SMS sending via live service, instead of logging. This changeset is needed for such case.

**Comment by atymic** [comment]
@klimov-paul 

How would you feel merging these PRs (this one, plus the exception one) into a new branch for v3 (with a dedicated / documented config file)?

**Comment by klimov-paul** [comment]
This is your call.
Although it might be better to re-implement feature from scratch in case new config approach to be implemented.

**Comment by gregoriohc** [comment]
Closing. This will be implemented in new v3 version as mentioned in PR #90

**Pull request closed without merging**
