### PR TITLE
Add/improve tests and improve testability

### PR DESCRIPTION
**Pull request by casperboone**
As this is currently the ~~second (you beat me, congratulations 😛)~~ most downloaded package, I thought the tests needed some attention to prove the working to its users.

**Note:** This PR proposes something a little different than #16. Pick what you like most ;).

I have done the following:
- Used a parallel test hierarchy for the message tests.
- Created tests for the channel
- Refactored `TwilioChannel` a little
- Created tests for the provider
- Changed the config helper method in the provider to $this->app['config']
- Changed `TwilioAbstractMessage` to `TwilioMessage`
- Created integration tests

### CODE REVIEW

**Comment by gregoriohc** [comment]
Do you want me to merge the pull request? Or are you adding more changes?
Thanks!

**Comment by casperboone** [comment]
I will add more ;)

**Comment by gregoriohc** [comment]
Great!

**Comment by casperboone** [comment]
@gregoriohc How do you think about changing `TwilioAbstractMessage` to just `TwilioMessage`? I think it makes more sense to see that `TwilioSmsMessage` inherits from `TwilioMessage` than from `TwilioAbstractMessage`, 'Abstract' doesn't really have a meaning and makes it less descriptive in my opinion.

**Comment by gregoriohc** [comment]
I agree @casperboone :-)

**Comment by casperboone** [comment]
Cool, will make the change. By the way, it may also be better to change `TwilioCallMessage` to `TwilioCall` I think, but since that is a breaking change, I'll leave that up to you ;).

**Comment by gregoriohc** [comment]
@casperboone I don't agree in that one... all notifications messages are just that, messages, so it's a good idea to name them with that suffix. In fact, all native laravel messages are named in that way (https://github.com/laravel/framework/tree/5.3/src/Illuminate/Notifications/Messages). 
Anyway, as you said, it's a breaking change, so I prefer to keep it with that name ;-)

**Comment by casperboone** [comment]
Kind of finished (don't merge yet). Is there anything you don't like? I'm happy to take a look at some things again ;).

**Comment by casperboone** [comment]
Since this PR is changing quite a lot, please try it out in an actual Laravel application before releasing it. I'm not a Twilio user myself, so I'm not able to actually use it. Please let me know if anything goes wrong, so I can fix it ;).

I prefer #17 over this PR , since #17 made the tests, but also the code in general a lot cleaner and more readable. However, it does introduce some changes you might not like. So, pick the one you like most ;).

**Comment by casperboone** [comment]
#17 it is ;)

**Pull request closed without merging**
